"""empty message

Revision ID: 73ee62a3857a
Revises: 8be4f54153da
Create Date: 2023-07-07 22:29:57.504385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73ee62a3857a'
down_revision = '8be4f54153da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ilustration', schema=None) as batch_op:
        batch_op.alter_column('url_image',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ilustration', schema=None) as batch_op:
        batch_op.alter_column('url_image',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###
