"""empty message

Revision ID: 8be4f54153da
Revises: 42015c7f18c1
Create Date: 2023-07-06 21:55:53.131176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8be4f54153da'
down_revision = '42015c7f18c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ilustration', schema=None) as batch_op:
        batch_op.alter_column('url_image',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ilustration', schema=None) as batch_op:
        batch_op.alter_column('url_image',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
